import json
import argparse

argparser = argparse.ArgumentParser(description='Extract proof names in scratch.v')
argparser.add_argument('--file', type=str, help='The json file generated by check_proofs.py, which contains all proof names.')
args = argparser.parse_args()

proof_names = json.load(open(args.file, 'r'))['proofs']

print('scratch.v include the following proofs: \n')
with open('proof_names.txt', 'w') as f:
    for name in proof_names:
        f.write(name + '\n')
        print(name)